#!/bin/bash

e () {
  echo "$@"
  eval "$@"
}

set -eu

zip=public_transport.zip
out=public_transport.mtx
if [ -f "$out" ] ; then
  echo "skip existing '$out'"
else
  e wget -nv -c "https://zenodo.org/record/3716134/files/DWV_2017_OeV_Wegematrizen_bin%C3%A4r.zip" -O "$zip"
  e unzip -p "$zip" "DWV_ЩV_2017_CH_binДr.mtx" \> "$out"
fi

zip=zones.zip
out=zones.gpkg
if [ -f "$out" ] ; then
  echo "skip existing '$out'"
else
  e wget -nv -c "https://zenodo.org/record/3716134/files/Verkehrszonen_Schweiz_NPVM_2017.zip" -O "$zip"
  tmp=$$.zip
  e unzip -p "$zip" "Verkehrszonen_Schweiz_NPVM_2017_gpkg.zip" \> "$tmp"
  e unzip -p "$tmp" "Verkehrszonen_Schweiz_NPVM_2017.gpkg" \> "$out"
  rm "$tmp"
fi
