#!/bin/bash

set -eu

name=growth
out=$name.pdf
files=$(ls *.pdf | grep -v "$name" | xargs)
cmd="pdfnup --nup 5x2 --outfile '$out' $files"
echo "$cmd"
eval "$cmd"

name=samples
out=samples.png
files=$(ls *.png | grep -v "$name" | xargs)
cmd="convert $files -set filename:fname '%t' \
-gravity North   -background LightGray  -splice 0x35 \
-pointsize 30 -annotate +0+4 '%[filename:fname]' \
miff:- | montage -background none -geometry +0+0 -tile 5x2 - $out"
echo "$cmd"
eval "$cmd"

cmd="convert samples-*.png samples.pdf"
echo "$cmd"
eval "$cmd"
