#!/bin/sh 
python -m korali.plotter --dir ./data/country.reparam.sir_int.tnrm/phase_1_results/_hierarchical/country.reparam.sir_int.tnrm/all_countriescountry.reparam.sir_int.tnrm/phase_3_results/ZH/country.reparam.sir_int.tnrm/_korali_samples_phase_3/ --output ./data/country.reparam.sir_int.tnrm/phase_1_results/_hierarchical/country.reparam.sir_int.tnrm/all_countriescountry.reparam.sir_int.tnrm/phase_3_results/ZH/country.reparam.sir_int.tnrm/figures/posterior.png
python -m korali.plotter --dir ./data/country.reparam.sir_int.tnrm/phase_1_results/_hierarchical/country.reparam.sir_int.tnrm/all_countriescountry.reparam.sir_int.tnrm/phase_3_results/BE/country.reparam.sir_int.tnrm/_korali_samples_phase_3/ --output ./data/country.reparam.sir_int.tnrm/phase_1_results/_hierarchical/country.reparam.sir_int.tnrm/all_countriescountry.reparam.sir_int.tnrm/phase_3_results/BE/country.reparam.sir_int.tnrm/figures/posterior.png
python -m korali.plotter --dir ./data/country.reparam.sir_int.tnrm/phase_1_results/_hierarchical/country.reparam.sir_int.tnrm/all_countriescountry.reparam.sir_int.tnrm/phase_3_results/LU/country.reparam.sir_int.tnrm/_korali_samples_phase_3/ --output ./data/country.reparam.sir_int.tnrm/phase_1_results/_hierarchical/country.reparam.sir_int.tnrm/all_countriescountry.reparam.sir_int.tnrm/phase_3_results/LU/country.reparam.sir_int.tnrm/figures/posterior.png
python -m korali.plotter --dir ./data/country.reparam.sir_int.tnrm/phase_1_results/_hierarchical/country.reparam.sir_int.tnrm/all_countriescountry.reparam.sir_int.tnrm/phase_3_results/FR/country.reparam.sir_int.tnrm/_korali_samples_phase_3/ --output ./data/country.reparam.sir_int.tnrm/phase_1_results/_hierarchical/country.reparam.sir_int.tnrm/all_countriescountry.reparam.sir_int.tnrm/phase_3_results/FR/country.reparam.sir_int.tnrm/figures/posterior.png
python -m korali.plotter --dir ./data/country.reparam.sir_int.tnrm/phase_1_results/_hierarchical/country.reparam.sir_int.tnrm/all_countriescountry.reparam.sir_int.tnrm/phase_3_results/BS/country.reparam.sir_int.tnrm/_korali_samples_phase_3/ --output ./data/country.reparam.sir_int.tnrm/phase_1_results/_hierarchical/country.reparam.sir_int.tnrm/all_countriescountry.reparam.sir_int.tnrm/phase_3_results/BS/country.reparam.sir_int.tnrm/figures/posterior.png
python -m korali.plotter --dir ./data/country.reparam.sir_int.tnrm/phase_1_results/_hierarchical/country.reparam.sir_int.tnrm/all_countriescountry.reparam.sir_int.tnrm/phase_3_results/BL/country.reparam.sir_int.tnrm/_korali_samples_phase_3/ --output ./data/country.reparam.sir_int.tnrm/phase_1_results/_hierarchical/country.reparam.sir_int.tnrm/all_countriescountry.reparam.sir_int.tnrm/phase_3_results/BL/country.reparam.sir_int.tnrm/figures/posterior.png
python -m korali.plotter --dir ./data/country.reparam.sir_int.tnrm/phase_1_results/_hierarchical/country.reparam.sir_int.tnrm/all_countriescountry.reparam.sir_int.tnrm/phase_3_results/TI/country.reparam.sir_int.tnrm/_korali_samples_phase_3/ --output ./data/country.reparam.sir_int.tnrm/phase_1_results/_hierarchical/country.reparam.sir_int.tnrm/all_countriescountry.reparam.sir_int.tnrm/phase_3_results/TI/country.reparam.sir_int.tnrm/figures/posterior.png
python -m korali.plotter --dir ./data/country.reparam.sir_int.tnrm/phase_1_results/_hierarchical/country.reparam.sir_int.tnrm/all_countriescountry.reparam.sir_int.tnrm/phase_3_results/VD/country.reparam.sir_int.tnrm/_korali_samples_phase_3/ --output ./data/country.reparam.sir_int.tnrm/phase_1_results/_hierarchical/country.reparam.sir_int.tnrm/all_countriescountry.reparam.sir_int.tnrm/phase_3_results/VD/country.reparam.sir_int.tnrm/figures/posterior.png
python -m korali.plotter --dir ./data/country.reparam.sir_int.tnrm/phase_1_results/_hierarchical/country.reparam.sir_int.tnrm/all_countriescountry.reparam.sir_int.tnrm/phase_3_results/VS/country.reparam.sir_int.tnrm/_korali_samples_phase_3/ --output ./data/country.reparam.sir_int.tnrm/phase_1_results/_hierarchical/country.reparam.sir_int.tnrm/all_countriescountry.reparam.sir_int.tnrm/phase_3_results/VS/country.reparam.sir_int.tnrm/figures/posterior.png
python -m korali.plotter --dir ./data/country.reparam.sir_int.tnrm/phase_1_results/_hierarchical/country.reparam.sir_int.tnrm/all_countriescountry.reparam.sir_int.tnrm/phase_3_results/NE/country.reparam.sir_int.tnrm/_korali_samples_phase_3/ --output ./data/country.reparam.sir_int.tnrm/phase_1_results/_hierarchical/country.reparam.sir_int.tnrm/all_countriescountry.reparam.sir_int.tnrm/phase_3_results/NE/country.reparam.sir_int.tnrm/figures/posterior.png
python -m korali.plotter --dir ./data/country.reparam.sir_int.tnrm/phase_1_results/_hierarchical/country.reparam.sir_int.tnrm/all_countriescountry.reparam.sir_int.tnrm/phase_3_results/GE/country.reparam.sir_int.tnrm/_korali_samples_phase_3/ --output ./data/country.reparam.sir_int.tnrm/phase_1_results/_hierarchical/country.reparam.sir_int.tnrm/all_countriescountry.reparam.sir_int.tnrm/phase_3_results/GE/country.reparam.sir_int.tnrm/figures/posterior.png
python -m korali.plotter --dir ./data/country.reparam.sir_int.tnrm/phase_1_results/_hierarchical/country.reparam.sir_int.tnrm/all_countriescountry.reparam.sir_int.tnrm/phase_3_results/GR/country.reparam.sir_int.tnrm/_korali_samples_phase_3/ --output ./data/country.reparam.sir_int.tnrm/phase_1_results/_hierarchical/country.reparam.sir_int.tnrm/all_countriescountry.reparam.sir_int.tnrm/phase_3_results/GR/country.reparam.sir_int.tnrm/figures/posterior.png
